# if a PR review or Issue Comment (must be PR) is from author, set to review required, otherwise if it's from someone in the reviewers group, set to author required

name: Remove Pending Author Label
on:
  pull_request_review_comment: 
    types: [created]

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v5
        id: get-reviewers
        with:
          github-token: ${{ secrets.ORG_READ }}
          script: |
            const {data: reviewerMembers} = await github.rest.teams.listMembersInOrg({
              org: context.payload.organization.login,
              team_slug: 'reviewers'
            });
            return reviewerMembers;
      - uses: actions/github-script@v5
        id: fix-is-reviewer-comment
        with:

          script: |
            const isReviewer = ${{steps.get-reviewers.outputs.result}}.some(({login}) => login === context.actor);
            if (!isReviewer) return;
            
            github.rest.issues.removeLabel({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: 'pending-review'
            });
            
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['pending-author-response']
            });
      - uses: actions/github-script@v5
        id: fix-labels-is-author
        with:

          script: |
            console.log(context)
            
            
