# on a review from someone in the reviewers group, remove the awaiting-review label and add the awaiting-author label
name: Remove pending review
on:
  pull_request_review:
    types: [submitted]

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.ORG_READ }}
          script: |
            const {data: reviewerMembers} = await github.rest.teams.listMembersInOrg({
              org: context.payload.organization.login,
              team_slug: 'reviewers'
            });
            
            const isReviewer = reviewerMembers.some(({login}) => login === context.actor);
            if (!isReviewer) return;
            
            github.rest.issues.removeLabel({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: 'pending-review'
            });
            
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['pending-author-response']
            });
            
